// Generated by CoffeeScript 1.3.3

/*
関数

function hello(){
	console.log "hello"
}

var hello = function(){
	console.log "hello"
}
*/


(function() {
  var hello;

  hello = function() {
    return console.log("hello");
  };

  hello();

  hello = function(s) {
    return console.log("hello!, " + s);
  };

  hello("taguchi");

  hello = function(s) {
    if (s == null) {
      s = "taguchi";
    }
    return console.log("hello! " + s);
  };

  hello();

  hello("Tom");

}).call(this);
