// Generated by CoffeeScript 1.3.3

/*
CoffeeScript

- varは不要
- 行末のセミコロンは不要
- 波括弧はインデントで表現
- 丸括弧は曖昧性がない場合は省略可能
*/


(function() {
  var message;

  message = 'Hello CoffeeScript!';

  if (message.length > 1) {
    console.log(message);
  }

}).call(this);
