// Generated by CoffeeScript 1.3.3

/*
配列、連想配列
*/


(function() {
  var a0, a1, a2, a3, a4, a5;

  a0 = [1, 2, 3, 5];

  console.log(a0);

  a1 = [1, 5, 8, 2, 4, 2];

  console.log(a1);

  a2 = {
    "sato": 100,
    "sasaki": 200
  };

  console.log(a2);

  a3 = {
    "sato": {
      "sales": 200,
      "cost": 80
    },
    "sasaki": {
      "sales": 250,
      "cost": 40
    }
  };

  console.log(a3);

  a4 = [1, 2, 3, 4, 5];

  console.log(a4);

  a5 = [1, 2, 3, 4];

  console.log(a5);

}).call(this);
