// Generated by CoffeeScript 1.3.3
(function() {
  var hello, name, s;

  hello = function() {
    return console.log("Hello, CoffeeScript!");
  };

  hello();

  /*
  文字列
  */


  s = "hello";

  console.log(s);

  s = "this is a pen. \nthis is a panda. \nthis is the end";

  console.log(s);

  name = "taguchi";

  console.log(name);

  console.log("hi, " + (15 / 3));

}).call(this);
