// Generated by CoffeeScript 1.3.3

/*
if文

* 比較演算子
is (===) isnt (!==)
not (!)
and (&&)
or (||)
*/


(function() {
  var x;

  x = 20;

  if ((10 < x && x < 30)) {
    console.log("true");
  }

  if ((10 < x && x < 30)) {
    console.log("true!");
  }

}).call(this);
