// Generated by CoffeeScript 1.3.3

/*
連想配列
*/


(function() {
  var key, sales, value;

  sales = {
    "tanaka": 100,
    "taguchi": 200,
    "sasaki": 300
  };

  for (key in sales) {
    value = sales[key];
    console.log("" + key + ":" + value);
  }

}).call(this);
