// Generated by CoffeeScript 1.3.3

/*
switch
*/


(function() {
  var signal;

  signal = "red";

  switch (signal) {
    case "red":
      console.log("stop!");
      break;
    case "green":
      console.log("go!");
      break;
    default:
      console.log("caution");
  }

}).call(this);
