// Generated by CoffeeScript 1.3.3

/*
if文
*/


(function() {
  var signal;

  signal = "red";

  if (signal === "red") {
    console.log("stop!");
  } else if (signal = "green") {
    console.log("go!");
  } else {
    console.log("caution!");
  }

}).call(this);
